"""books table

Revision ID: 4ea76d5faa43
Revises: bca801053f20
Create Date: 2020-06-28 18:08:56.552573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea76d5faa43'
down_revision = 'bca801053f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('homepage_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'homepage_image_url')
    # ### end Alembic commands ###
