"""people table

Revision ID: 8c35744c77c7
Revises: 513f5a49ce12
Create Date: 2020-06-19 18:40:32.556361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c35744c77c7'
down_revision = '513f5a49ce12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_reviews', sa.Column('score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_reviews', 'score')
    # ### end Alembic commands ###
