"""books table

Revision ID: a04d2cef1b96
Revises: bf83901ed683
Create Date: 2020-06-25 21:23:25.748430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04d2cef1b96'
down_revision = 'bf83901ed683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('asin', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('gr_bookid', sa.String(), nullable=True))
    op.add_column('books', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.String(), nullable=True))
    op.add_column('books', sa.Column('kindle_asin', sa.String(), nullable=True))
    op.add_column('books', sa.Column('stars_1', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('stars_2', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('stars_3', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('stars_4', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('stars_5', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'thumbnail_url')
    op.drop_column('books', 'stars_5')
    op.drop_column('books', 'stars_4')
    op.drop_column('books', 'stars_3')
    op.drop_column('books', 'stars_2')
    op.drop_column('books', 'stars_1')
    op.drop_column('books', 'kindle_asin')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'image_url')
    op.drop_column('books', 'gr_bookid')
    op.drop_column('books', 'description')
    op.drop_column('books', 'asin')
    # ### end Alembic commands ###
