"""books table

Revision ID: b6ce4fea67bf
Revises: 83660dba68af
Create Date: 2020-06-26 10:22:06.392329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ce4fea67bf'
down_revision = '83660dba68af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
