"""books table

Revision ID: bca801053f20
Revises: b69db333d163
Create Date: 2020-06-28 16:44:29.501472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca801053f20'
down_revision = 'b69db333d163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'google_image_url')
    # ### end Alembic commands ###
