"""books table

Revision ID: bd1fd771d818
Revises: bf83901ed683
Create Date: 2020-06-24 21:32:18.521503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1fd771d818'
down_revision = 'bf83901ed683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('Stars_1', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('Stars_2', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('Stars_3', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('Stars_4', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('Stars_5', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('asin', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('grBookID', sa.String(), nullable=True))
    op.add_column('books', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.String(), nullable=True))
    op.add_column('books', sa.Column('kindle_asin', sa.String(), nullable=True))
    op.add_column('books', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'thumbnail_url')
    op.drop_column('books', 'kindle_asin')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'image_url')
    op.drop_column('books', 'grBookID')
    op.drop_column('books', 'description')
    op.drop_column('books', 'asin')
    op.drop_column('books', 'Stars_5')
    op.drop_column('books', 'Stars_4')
    op.drop_column('books', 'Stars_3')
    op.drop_column('books', 'Stars_2')
    op.drop_column('books', 'Stars_1')
    # ### end Alembic commands ###
