"""books table

Revision ID: c7d2586dfaa2
Revises: a04d2cef1b96
Create Date: 2020-06-25 21:38:27.927239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d2586dfaa2'
down_revision = 'a04d2cef1b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('lookup_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'lookup_id')
    # ### end Alembic commands ###
