"""books table

Revision ID: e2edcb89db6f
Revises: bd1fd771d818
Create Date: 2020-06-25 15:39:14.452604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2edcb89db6f'
down_revision = 'bd1fd771d818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('bookID', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'bookID')
    # ### end Alembic commands ###
